baseURL = 'https://blog.okanvurdu.com'
languageCode = 'tr-tr'
title = 'okan vurdu - blog'
theme = 'vit'
timeZone = 'Europe/Istanbul'
defaultContentLanguage = "tr"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = '/p/:slug/'
